// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgspVh1cXOmSS9-gRu6o39r8VLKfxTQXU',
    appId: '1:543054746191:web:39f4e621012d485d86103a',
    messagingSenderId: '543054746191',
    projectId: 'shopapp-83067',
    authDomain: 'shopapp-83067.firebaseapp.com',
    storageBucket: 'shopapp-83067.firebasestorage.app',
    measurementId: 'G-QH6WKGV36D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgeEifNMYti39AzRhN1fU4YJLoROJW1cc',
    appId: '1:543054746191:android:d9889c76552291c786103a',
    messagingSenderId: '543054746191',
    projectId: 'shopapp-83067',
    storageBucket: 'shopapp-83067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0qRA88lkNZNqnG9y6lxxPNtNUxqFb0s',
    appId: '1:543054746191:ios:1d7c5d5659a53eb986103a',
    messagingSenderId: '543054746191',
    projectId: 'shopapp-83067',
    storageBucket: 'shopapp-83067.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM0qRA88lkNZNqnG9y6lxxPNtNUxqFb0s',
    appId: '1:543054746191:ios:1d7c5d5659a53eb986103a',
    messagingSenderId: '543054746191',
    projectId: 'shopapp-83067',
    storageBucket: 'shopapp-83067.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgspVh1cXOmSS9-gRu6o39r8VLKfxTQXU',
    appId: '1:543054746191:web:a7ccf754ad01c04c86103a',
    messagingSenderId: '543054746191',
    projectId: 'shopapp-83067',
    authDomain: 'shopapp-83067.firebaseapp.com',
    storageBucket: 'shopapp-83067.firebasestorage.app',
    measurementId: 'G-NYF47BSEK7',
  );

}